export const BANNER =
  "<!-- Generated by arch-crew: runtime/baseline/build-constitution.mjs. Do not edit by hand. -->";

function pad(id) {
  return String(id).padStart(4, "0");
}

// In `adr` mode a decision's filename is a file in the sibling decisions/
// directory. In `living` mode it is already a `path#anchor` relative to the
// project root, and the rollup sits beside the document, so the document's own
// directory prefix is dropped to keep the link relative to this file.
function sourceLink(decision, mode) {
  if (mode !== "living") return `decisions/${decision.filename}`;
  const slash = decision.filename.lastIndexOf("/");
  return slash === -1 ? decision.filename : decision.filename.slice(slash + 1);
}

function verificationNote(rule) {
  if (rule.verification === "deterministic") {
    return (
      `Verified by \`${rule.verifiedBy}\` — run the rule checker to resolve this binding and evaluate it. ` +
      "The checker's verdict covers the whole repository, not only this rule's scope: `scope` decides which " +
      "edits the drift drain treats as touching this rule, never what the checker itself inspects."
    );
  }
  if (rule.verification === "review") {
    return "Verified by review — needs judgement, and may be graded as a soft signal.";
  }
  return "Narrative intent — **not** verifiable. Do not grade compliance against it.";
}

// `mode` changes exactly one thing: the sentence naming where the human record
// lives, and how each rule links back to it. Every rule, severity, scope and
// verification note below is MACHINE ENFORCEMENT METADATA and is rendered
// identically whichever mode produced it -- a diff of this file between the two
// modes shows the source links and nothing else.
export function renderConstitution(decisions, { mode = "adr" } = {}) {
  const active = decisions.filter((decision) => decision.status === "active");
  const byId = new Map(active.map((decision) => [decision.id, decision]));
  const rules = active
    .flatMap((decision) => decision.rules)
    .sort((left, right) => (left.id < right.id ? -1 : left.id > right.id ? 1 : 0));

  const lines = [
    BANNER,
    "",
    "# Architecture Constitution",
    "",
    mode === "living"
      ? "The active rules of this repository, rolled up from the living architecture documents that state them."
      : "The active rules of this repository, rolled up from the decision files that state them.",
    mode === "living"
      ? "Edit the living document and regenerate; never edit this file."
      : "Edit a decision file and regenerate; never edit this file.",
    "",
    "## Rules",
    "",
  ];

  if (rules.length === 0) {
    lines.push("_No active rules yet._", "");
  }

  for (const rule of rules) {
    const decision = byId.get(rule.decision);
    lines.push(`### ${rule.id}`, "");
    lines.push(rule.statement, "");
    lines.push(`- Severity: ${rule.severity}`);
    if (rule.scope.length > 0) {
      lines.push(`- Scope: ${rule.scope.map((entry) => `\`${entry}\``).join(", ")}`);
    }
    lines.push(`- ${verificationNote(rule)}`);
    lines.push(`- Source: [${pad(decision.id)} ${decision.title}](${sourceLink(decision, mode)})`);
    lines.push("");
  }

  lines.push("## Active decisions", "");
  for (const decision of [...active].sort((left, right) => left.id - right.id)) {
    lines.push(`- [${pad(decision.id)} ${decision.title}](${sourceLink(decision, mode)}) — ${decision.skill}`);
  }
  lines.push("");

  return lines.join("\n");
}
