export const BANNER =
  "<!-- Generated by arch-crew: runtime/baseline/build-constitution.mjs. Do not edit by hand. -->";

function pad(id) {
  return String(id).padStart(4, "0");
}

function verificationNote(rule) {
  if (rule.verification === "deterministic") {
    return `Verified by \`${rule.verifiedBy}\` — run the rule checker to resolve this binding and evaluate it.`;
  }
  if (rule.verification === "review") {
    return "Verified by review — needs judgement, and may be graded as a soft signal.";
  }
  return "Narrative intent — **not** verifiable. Do not grade compliance against it.";
}

export function renderConstitution(decisions) {
  const active = decisions.filter((decision) => decision.status === "active");
  const byId = new Map(active.map((decision) => [decision.id, decision]));
  const rules = active
    .flatMap((decision) => decision.rules)
    .sort((left, right) => (left.id < right.id ? -1 : left.id > right.id ? 1 : 0));

  const lines = [
    BANNER,
    "",
    "# Architecture Constitution",
    "",
    "The active rules of this repository, rolled up from the decision files that state them.",
    "Edit a decision file and regenerate; never edit this file.",
    "",
    "## Rules",
    "",
  ];

  if (rules.length === 0) {
    lines.push("_No active rules yet._", "");
  }

  for (const rule of rules) {
    const decision = byId.get(rule.decision);
    lines.push(`### ${rule.id}`, "");
    lines.push(rule.statement, "");
    lines.push(`- Severity: ${rule.severity}`);
    if (rule.scope.length > 0) {
      lines.push(`- Scope: ${rule.scope.map((entry) => `\`${entry}\``).join(", ")}`);
    }
    lines.push(`- ${verificationNote(rule)}`);
    lines.push(`- Source: [${pad(decision.id)} ${decision.title}](decisions/${decision.filename})`);
    lines.push("");
  }

  lines.push("## Active decisions", "");
  for (const decision of [...active].sort((left, right) => left.id - right.id)) {
    lines.push(`- [${pad(decision.id)} ${decision.title}](decisions/${decision.filename}) — ${decision.skill}`);
  }
  lines.push("");

  return lines.join("\n");
}
